Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace JobOfferWebiste.Models
{
    public class Job
    {
        public int Id { get; set; }

        
        [Required]
        [DisplayName("Trip Title")]
        public string TripTitle { get; set; }

        [Required]
        [DisplayName("Trip Details")]
        [AllowHtml]
        public string TripDetails { get; set; }
        
       


        [Required]
        [DisplayName("Types of Trips")]
        public int CategoryId { get; set; }


        [Required]
        [DisplayName("Agency Name")]
        [AllowHtml]
        public string AgencyName { get; set; }


        public DateTime PostDate { get; set; }

        [Required]
        [DisplayName("Trip Date")]
        public string TripDate { get; set; }

        [Required]
        [DisplayName("Trip Destination")]
        public string TripDestination { get; set; }

        
        [DisplayName("Trip Image")]
        public string TripImage { get; set; }

        public string Price { get; set; }
        public string UserID { get; set; }
        
        public virtual Category Category { get; set; }
        
        public virtual ApplicationUser User { get; set; }
    }
}

Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobOfferWebiste.Models;
using WebApplication1.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace Job_Offers_Website.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobs
        public ActionResult Index()
        {
            var jobs = db.Jobs.Include(j => j.Category);
            return View(jobs.ToList());
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                job.TripImage = upload.FileName;
                job.PostDate = DateTime.Now;
                job.UserID = User.Identity.GetUserId();
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string oldPath = Path.Combine(Server.MapPath("~/Uploads"), job.TripImage);

                if (upload != null)
                {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    job.TripImage = upload.FileName;
                }
                job.PostDate = DateTime.Now;


                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }





        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Jobs/Create.cshtml
@model JobOfferWebiste.Models.Job

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Create</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("Create", "Jobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Job</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TripTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TripTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TripTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TripDetails, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TripDetails, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TripDetails, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgencyName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TripDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TripDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TripDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TripDestination, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TripDestination, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TripDestination, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TripImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload" />
            @Html.ValidationMessageFor(model => model.TripImage, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "نوع الوظيفة", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Jobs/Delete.cshtml
@model JobOfferWebiste.Models.Job

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>حذف الوظيفة</h2>

<h3>Are you sure that you want to delete this trip`s post?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TripTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TripTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TripDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TripDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TripImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model=>model.TripImage)"
                 class="thumbnail"
                 style="width:48px; height:48px;" />
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.AgencyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.TripDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TripDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TripDestination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TripDestination)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="تأكيد الحذف" class="btn btn-danger" /> |
            @Html.ActionLink("Back to the Trips", "Index")
        </div>
    }
</div>

Views/Jobs/Details.cshtml
@*@model JobOfferWebiste.Models.Job

    @{
        ViewBag.Title = "Details";
        Layout = "~/Views/Shared/_MainLayout.cshtml";
    }

    <h2>Details</h2>

    <div>
        <h4>Job</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Category.CategoryName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Category.CategoryName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TripTitle)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TripTitle)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AgencyName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AgencyName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TripDetails)
            </dt>

            <dd>
                @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.TripDetails).ToString()))

            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TripDestination)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TripDestination)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PostDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PostDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.TripImage)
            </dt>

            <dd>
                <img src="~/Uploads/@Html.DisplayFor(model=>model.TripImage)"
                     class="thumbnail"
                     style="width:48px; height:48px;" />
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("A", "AddAgencyComment", new { id = Model.Id }, new { @class = "btn btn-success" })
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id } , new { @class = "btn btn-success" }) |
        @Html.ActionLink("Back to List", "Index" , new { @class = "btn btn-success" })
    </p>*@



@model JobOfferWebiste.Models.Job


@{
    ViewBag.Title = "Detailse";
    Layout = "~/Views/shared/_MainLayout.cshtml";
}

<h2>Detailse</h2>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.TripTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TripTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AgencyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TripDetails)
        </dt>

        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.TripDetails).ToString()))

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TripDestination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TripDestination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TripImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model=>model.TripImage)"
                 class="thumbnail"
                 style="width:48px; height:48px;" />
        </dd>


       

    </dl>
</div>


<p>
   
    @Html.ActionLink("Agency Add Comment", "AddAgencyComment", new { id = Model.Id }, new { @class = "btn btn-success" })
    @Html.ActionLink("Back To The Home", "Index", new { id = Model.Id }, new { @class = "btn btn-success" })



</p>

Views/Jobs/Edit.cshtml
@model JobOfferWebiste.Models.Job

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Jobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <div class="alert alert-danger" id="error-div" style="display:none">
        <span id="view-err">

        </span>
    </div>




    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.TripImage)

    <div class="form-group">
        @Html.LabelFor(model => model.TripTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TripTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TripTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TripDetails, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TripDetails, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TripDetails, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.TripDestination, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TripDestination, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TripDestination, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AgencyName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TripDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TripDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TripDate, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.TripImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload" id="myImage" />
            @Html.ValidationMessageFor(model => model.TripImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" id="save" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section scripts{
    <script>
        $(function () {
            $("#save").click(function () {

                //Check if the input is Empty
                //if ($("#JobImage").val() == "") {
                //    $("#error-div").fadeIn();
                //    $("#view-err").append("رجاء قم باختيار صورة");
                //    return false;
                //}

                if ($("#myImage").val() != "") {
                    //Check if the Image extension is valid
                    var filename = document.getElementById("myImage").value;
                    var extensionImg = filename.substr(filename.lastIndexOf('.') + 1);
                    var validExtensions = ['jpg', 'png', 'gif', 'bmp'];
                    if ($.inArray(extensionImg, validExtensions) == -1) {
                        $("#error-div").fadeIn();
                        $("#view-err").append("رجاء قم باختيار صورة بامتداد صحيح");
                        return false;
                    }

                    //Check if the Image Size is valid (2 mb)
                    var myFileSize = document.getElementById("myImage").files[0].size / 1024 / 1024;

                    if (myFileSize > 2) {
                        $("#error-div").fadeIn();
                        $("#view-err").append("رجاء قم باختيار صورة حجمها أقل من 2 ميغا بايت");
                        return false;
                    }
                }
            });
        });
    </script>

}

Views/Jobs/Index.cshtml
@model IEnumerable<JobOfferWebiste.Models.Job>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>قائمة الوظائف</h2>

<p>
    @Html.ActionLink("Create New Tripre", "Create")
</p>
<table class="table table-stripped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TripTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TripDetails)
        </th>
        <th style=" width:100px; ">
            @Html.DisplayNameFor(model => model.TripImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TripDestination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TripDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AgencyName)
        </th>
        <th>
            Post Date
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>

    </tr>

@foreach (var item in Model) {
   
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Category.CategoryName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TripTitle)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.User.UserName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TripDetails)
    </td>
    <td>
        <img src="~/Uploads/@Html.DisplayFor(model=>item.TripImage)"
             class="thumbnail" style="width:48px; height:48px" />
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.TripDestination)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.TripDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.AgencyName)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.PostDate)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.Price)
    </td>

    <td>
        @Html.ActionLink("Edit         ", "Edit", new { id = item.Id }) <br /> <br />
        @Html.ActionLink("Details      ", "Details", new { id = item.Id }) <br /> <br />
        @Html.ActionLink("Delete       ", "Delete", new { id = item.Id })
    </td>
</tr>
}

</table>